version: '2'
services:
  api:
    container_name: todoreminder
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
     environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: dc60d6c5ed27ef1a
      - URI
      - SMTP_PASSWORD
      - BASE_URL

    volumes:
      - storage_dev:/app/storage
    ports:
      - "8080:8080"

volumes:
  storage_dev:
