version: '2'
services:
  api:
    container_name: todoreminder
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
     environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql.ardijorganxhi.dev/todoreminder
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=dc60d6c5ed27ef1a
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      

    volumes:
      - storage_dev:/app/storage
    ports:
      - "8080:8080"

volumes:
  storage_dev:
